/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
import java.util.*;
/**
 *
 * @author Jack
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form loginAdmin
     */
    public login() {
        initComponents();
    }
    
   private void errorMsg(String msg) {
   	JOptionPane optionPane = new JOptionPane(msg, JOptionPane.ERROR_MESSAGE);    
   	JDialog dialog = optionPane.createDialog("Failure");
   	dialog.setAlwaysOnTop(true);
   	dialog.setVisible(true);
   	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jTextField1.setText("Username");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        graphicInt a = new graphicInt();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

        public void setmyAccount(String a){
        
        String myAccount2 = a;
       
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //char[] password = jPasswordField1.getPassword();
        String myPass = String.valueOf(jPasswordField1.getPassword());
        String myAccount  = String.valueOf(jTextField1.getText());
        datorBas a = new datorBas();
        a.DBHandler();
        String adminUserName = a.sendQueryUsernameAdmin("select aId from admin where aId ='" + myAccount + "'");
        String guideUserName = a.sendQueryUsernameGuide("select gId from guide where gId ='" + myAccount + "'");
        String customerUserName = a.sendQueryUsernameCustomer("select cId from custumer where cId ='" + myAccount + "'");
        
        // LOGIN FÖR ADMIN
            if (!adminUserName.equals(myAccount)){
          //      System.out.println("This is not a correct admin username!");
            }

            else {
             System.out.println(adminUserName);
             String adminPassword = a.sendQueryPasswordAdmin("select aPassword from admin where aId ='" + myAccount + "'");
                if (!adminPassword.equals(myPass)){
         //       System.out.println("Wrong Password!");
                    }
                else {  
         //           System.out.println("Correct password!");
         //           System.out.println("ÖPPNA ADMININTERFACE!" + "\n");
                    windowAdmin p = new windowAdmin();
                    p.setVisible(true);
                    this.dispose();
                    
                }
            }
            
            // LOGIN FÖR GUIDE
            if (!guideUserName.equals(myAccount)){
       //         System.out.println("This is not a correct guide username!");
            }

            else {
             System.out.println(guideUserName);
             String guidePassword = a.sendQueryPasswordGuide("select gPassword from guide where gId ='" + myAccount + "'");
                if (!guidePassword.equals(myPass)){
              //  System.out.println("Wrong Password for guide!");
                    }
                else {  
                  //  System.out.println("Correct password!");
                //    System.out.println("ÖPPNA guideuserface!" + "\n");
                                        windowGuide p = new windowGuide();
                    p.setVisible(true);
                    this.dispose();
                }
            }
         // LOGIN FÖR CUSTOMER
            if (!customerUserName.equals(myAccount)){
              //  System.out.println("This is not a correct Customer username!");
            }

            else {
                System.out.println(customerUserName);
                String customerPassword = a.sendQueryPasswordCustomer("select cPassword from custumer where cId ='" + myAccount + "'");
                   if (!customerPassword.equals(myPass)){
                 
                   }
                   else {  
                       
        
        
        
        
                    login x = new login();
                    //.setmyAccount(myAccount);
                   
                       
                    windowCustomer p = new windowCustomer(myAccount);
                    p.setVisible(true);
                    this.dispose();
                   }
                   System.out.println("errorkompis");
            }
           
       
       
            
        
        
       /* if (myPass.equals("safarier")){
         adminFrame g = new adminFrame();
         g.setVisible(true);
        this.dispose();
        }
        else{
        errorMsg("Wrong Password");
       
        
        } */
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
     public String getmyAccount(){
        
        String myAccount = String.valueOf(jTextField1.getText());
        return myAccount;
    }
     
     
    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
